# Generated by Django 3.2.7 on 2021-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_auto_20210918_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
