# Generated by Django 3.2.7 on 2021-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_auto_20210918_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
