# Generated by Django 3.2.7 on 2021-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_auto_20210918_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
