# Generated by Django 3.2.7 on 2021-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_auto_20210918_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
